// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwCTorVheGfIVPjWSnZJHKu7PE930Ncoo',
    appId: '1:779215032248:web:4be46e353381877b51494d',
    messagingSenderId: '779215032248',
    projectId: 'danenergymonitor',
    authDomain: 'danenergymonitor.firebaseapp.com',
    storageBucket: 'danenergymonitor.appspot.com',
    measurementId: 'G-YJGDGVP1H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxLcQFS7yENUKPM0un1sDxQVzTtG1bnw4',
    appId: '1:779215032248:android:8664ac9d8cb0d36051494d',
    messagingSenderId: '779215032248',
    projectId: 'danenergymonitor',
    storageBucket: 'danenergymonitor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXk4x0ZDbU4SgLL7ayvnqfeIjB9eUJnLQ',
    appId: '1:779215032248:ios:2d57a4849e02603e51494d',
    messagingSenderId: '779215032248',
    projectId: 'danenergymonitor',
    storageBucket: 'danenergymonitor.appspot.com',
    iosBundleId: 'com.example.danEnergyMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXk4x0ZDbU4SgLL7ayvnqfeIjB9eUJnLQ',
    appId: '1:779215032248:ios:3620e66982f2dd2751494d',
    messagingSenderId: '779215032248',
    projectId: 'danenergymonitor',
    storageBucket: 'danenergymonitor.appspot.com',
    iosBundleId: 'com.example.danEnergyMonitor.RunnerTests',
  );
}
